In [5]:
import numpy as np
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
np.matmul(array1,array2)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-17,  1.00000000e+00]])

In [6]:
w , v =np.linalg.eig(array1)
#特徵值
w

array([13.,  2.])

In [7]:
#特徵向量
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [8]:
u, s, vh = np.linalg.svd(array1)
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [9]:
s

array([13.94721714,  1.86417116])

In [10]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])